server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ycloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
